# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
kafka_version <- function() {
    .Call(`_rkafka_kafka_version`)
}

#' @export
kafka_conf_new <- function() {
    .Call(`_rkafka_kafka_conf_new`)
}

#' @export
kafka_conf_set <- function(p, k, v) {
    .Call(`_rkafka_kafka_conf_set`, p, k, v)
}

#' @export
kafka_conf_destroy <- function(p) {
    invisible(.Call(`_rkafka_kafka_conf_destroy`, p))
}

#' @export
kafka_topic_conf_new <- function() {
    .Call(`_rkafka_kafka_topic_conf_new`)
}

#' @export
kafka_topic_conf_set <- function(p, k, v) {
    .Call(`_rkafka_kafka_topic_conf_set`, p, k, v)
}

#' @export
kafka_topic_conf_destroy <- function(p) {
    invisible(.Call(`_rkafka_kafka_topic_conf_destroy`, p))
}

#' @export
kafka_consumer_new <- function(p_conf) {
    .Call(`_rkafka_kafka_consumer_new`, p_conf)
}

#' @export
kafka_producer_new <- function(p_conf) {
    .Call(`_rkafka_kafka_producer_new`, p_conf)
}

#' @export
kafka_destroy <- function(p) {
    invisible(.Call(`_rkafka_kafka_destroy`, p))
}

#' @export
kafka_topic_new <- function(p_client, name, p_conf) {
    .Call(`_rkafka_kafka_topic_new`, p_client, name, p_conf)
}

#' @export
kafka_topic_destroy <- function(p) {
    invisible(.Call(`_rkafka_kafka_topic_destroy`, p))
}

#' @export
kafka_produce <- function(p_topic, partition, payload, key) {
    .Call(`_rkafka_kafka_produce`, p_topic, partition, payload, key)
}

#' @export
kafka_produce_batch <- function(p_topic, partition, batch) {
    .Call(`_rkafka_kafka_produce_batch`, p_topic, partition, batch)
}

#' @export
kafka_consume_batch <- function(p_topic, partition, timeout) {
    .Call(`_rkafka_kafka_consume_batch`, p_topic, partition, timeout)
}

#' @export
kafka_consume_start <- function(p_topic, partition, offset) {
    .Call(`_rkafka_kafka_consume_start`, p_topic, partition, offset)
}

#' @export
kafka_consume_stop <- function(p_topic, partition) {
    .Call(`_rkafka_kafka_consume_stop`, p_topic, partition)
}

#' @export
kafka_flush <- function(p_client, timeout) {
    .Call(`_rkafka_kafka_flush`, p_client, timeout)
}

#' @export
kafka_subscribe <- function(p_client, topics) {
    .Call(`_rkafka_kafka_subscribe`, p_client, topics)
}

#' @export
kafka_unsubscribe <- function(p_client) {
    .Call(`_rkafka_kafka_unsubscribe`, p_client)
}

#' @export
kafka_consumer_poll <- function(p_client, timeout) {
    .Call(`_rkafka_kafka_consumer_poll`, p_client, timeout)
}

#' @export
kafka_consumer_close <- function(p_client) {
    .Call(`_rkafka_kafka_consumer_close`, p_client)
}

